### ISSUE TITLE
Add some deployment examples

### ISSUE THREAD

**Issue by pieterlange** [gianrubio/aws-share-rds-snapshot#4]
Add some very basic deployment examples:

* Deploy in old-timey (and reliable) vixie-cron-esque environment
* Deploy as kubernetes cronjob
* Lambda
* ..

**Comment by gianrubio** [comment]
Done https://github.com/gianrubio/aws-share-rds-snapshot/tree/618c1183200a78296d4780d1e715eb23e23bf26e/k8s
